version: '3'
services:
  nginx:
    image: ghcr.io/ufal/dockerized-nginx-with-shibboleth/nginx-shib:latest
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    # TODO logs
    # generate /ssl/dhparam.pem with openssl dhparam -out dhparam.pem 4096
      - ./nginx/templates:/etc/nginx/templates # TODO add to conf
      - ./nginx/locations:/etc/nginx/locations
      - ./nginx/ssl:/ssl
    environment:
      - NGINX_ENVSUBST_FILTER=NGINX_
      - NGINX_SHIBAUTHORIZER=${NGINX_SHIBAUTHORIZER:-shibboleth:12345}
      - NGINX_SHIBRESPONDER=${NGINX_SHIBRESPONDER:-shibboleth:12345}
      - NGINX_TOMCAT
      - NGINX_NODE
      - NGINX_SERVER_NAMES
      - NGINX_RESOLVERS
    depends_on:
      - shibboleth

  shibboleth:
    image: ghcr.io/ufal/dockerized-nginx-with-shibboleth/shibboleth:latest
    build: ./shibboleth
    volumes:
    # config (+key material), logs
    - ./shibboleth/overrides:/overrides
    - ./shibboleth/sp-keys:/sp-keys
    - logs:/opt/shibboleth-sp/var/log
    environment:
     - SHIB_HOSTNAME=${SHIB_HOSTNAME:?SHIB_HOSTNAME must be set}

volumes:
  logs:
